# Use Ctrl-A as prefix key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Ctrl-A R to reload config
unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "battery ram-usage cpu-usage"
set -g @dracula-show-location false
# set -g @dracula-border-contrast true
set -g @dracula-show-fahrenheit false
set -g @dracula-battery-label "⚡️"

# set-option -ag status-right-style "bg=colour33"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


# Inactive pane colours
set -g window-style 'bg=color234, fg=default'
set -g window-active-style 'bg=color232, fg=default'
set pane-border-style 'bg=color234, fg=terminal'
set pane-active-border-style 'bg=color234, fg=cyan'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
